### ISSUE TITLE
When I hit install...

### ISSUE THREAD

**Issue by GamingInfinite** [Narua2010/AmongUsModUpdater#17]
I made sure that my antivirus wasn't doing anything weird to the installer but the installer still crashes whenever I hit install.  The setup.exe wasn't working earlier as well, but it was an antivirus issue so I restored it with an exception and it worked fine.

https://pastebin.com/qJyCkdad

That paste has what is under the Details button when it crashes.  I can leave a screenshot as well if needed.  I will keep checking if it has something to do with my antivirus as it doesn't like other executables modifying anything.

**Comment by Eisbison** [comment]
Might be because the zip of the previous version was zipped differently (since it wasn't me making the release). I'll rezip and update the release later, then we'll see if that resolves the issue.

**Comment by Narua2010** [comment]
@Eisbison , you beat me to it 👍  

now we have 2 options: you make sure that the structure matches again or I adjust the structure in the updater. Keep me posted on what is more convenient for you.

I can definitely say that it's because of the new version of TOR. You now have another folder in which you load the mod data. Before, all the data was directly in the root directory, which is why the updater fails.

**Comment by Eisbison** [comment]
I'll fix the structure 👍  The team just had to rush a release yesterday because of a few mayor bugs, and packaged the thing differently. I'll get home in two hours and will udate the release immediately.

**Comment by Eisbison** [comment]
I think the issue can be closed 👍

**Comment by Narua2010** [comment]
The folder structure of TOR has been restored so that the updater does not throw an error.
